package com.rage.siapp.nlp.tools.network;

public enum EdgeType 
{
	INTRA_CLAUSE,
	INTER_CLAUSE_INTRA_SENTENCE,
	INTER_CLAUSE_INTER_SENTENCE,
	INTER_CLAUSE_INTER_SENTENCE_INTRA_DOCUMENT,
	INTER_CLAUSE_INTER_SENTENCE_INTER_DOCUMENT,
	NONE
}
